name : Deploy to Render

on:
   push:
    branches: 
        - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: "3.9.13"

        - name: Install Dependencies
          run: |
            pip install --upgrade pip
            pip install -r requirements.txt   
            
        - name: Deploy to Render
          env:
            RENDER_API_KEY: ${{secrets.RENDER_API_KEY}}      
            RENDER_SERVICE_ID: ${{secrets. RENDER_SERVICE_ID}}
          run: |
            curl -X POST https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploy \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -F "file=@path_to_your_deployment_file" \  # Path to the deployment file
            -F "branch=master"  # Specifying the branch to deploy  
